INSERT INTO DEPARTMENT (DEPT_NAME, BUILDING, BUDGET) VALUES ('Biology', 'Watson', 90000.00);
INSERT INTO DEPARTMENT (DEPT_NAME, BUILDING, BUDGET) VALUES ('Comp.Sci.', 'Taylor', 100000.00);
INSERT INTO DEPARTMENT (DEPT_NAME, BUILDING, BUDGET) VALUES ('Elec.Eng.', 'Taylor', 85000.00);
INSERT INTO DEPARTMENT (DEPT_NAME, BUILDING, BUDGET) VALUES ('Finance', 'Painter', 120000.00);
INSERT INTO DEPARTMENT (DEPT_NAME, BUILDING, BUDGET) VALUES ('History', 'Painter', 50000.00);
INSERT INTO DEPARTMENT (DEPT_NAME, BUILDING, BUDGET) VALUES ('Music', 'Packard', 80000.00);
INSERT INTO DEPARTMENT (DEPT_NAME, BUILDING, BUDGET) VALUES ('Physics', 'Watson', 70000.00);