// Automatically generated by com.ling.learn0806.processor.ToStringAnnotationProcessor
package com.ling.learn0806.processor;
public class ToStrings {
    public static String toString(com.ling.learn0806.srcdemo.Point obj) {
        StringBuilder result = new StringBuilder();
        result.append("[");
        result.append(toString(obj.getX()));
        result.append(",");
        result.append(toString(obj.getY()));
        result.append("]");
        return result.toString();
    }
    public static String toString(com.ling.learn0806.srcdemo.Rectangle obj) {
        StringBuilder result = new StringBuilder();
        result.append("com.ling.learn0806.srcdemo.Rectangle");
        result.append("[");
        result.append(toString(obj.getTopLeft()));
        result.append(",");
        result.append("width=");
        result.append(toString(obj.getWidth()));
        result.append(",");
        result.append("height=");
        result.append(toString(obj.getHeight()));
        result.append("]");
        return result.toString();
    }
    public static String toString(Object obj) {
        return java.util.Objects.toString(obj);
    }
}
