CREATE TABLE CJ_USER(
	USERID INTEGER NOT NULL, 
	UNAME VARCHAR(20), 
	CONSTRAINT PK_USER PRIMARY KEY (USERID)
	);

INSERT INTO CJ_USER VALUES(1,'ling');
INSERT INTO CJ_USER VALUES(2,'pengmz');
INSERT INTO CJ_USER VALUES(3,'linsc');
INSERT INTO CJ_USER VALUES(4,'tanxq');
INSERT INTO CJ_USER VALUES(5,'linzy');

DROP TABLE CJ_USER;